{% set python_min = '3.10' %}
{% set name = "pytest-xflaky" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_xflaky-{{ version }}.tar.gz
  sha256: c5341021a47169a12975811b95809eada682a9ae33cfa93402b1c3499164efbe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pytest-json-report
    - pytest >=8.2.1
    - requests
    - tree_sitter
    - tree-sitter-python

test:
  imports:
    - pytest_xflaky
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Tesorio/pytest-xflaky
  summary: A flaky-test hunter pytest plugin that collects reports and automatically submits PRs to put flaky tests under quarantine.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
